In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("../data/raw/Daily_Power_Gen_Source_march_23.csv")
df.head()

         source     NR     WR     SR     ER   NER  All India        date
0         Hydro  139.0   43.0   72.0   30.0   7.0        292  2013-03-31
1         Total  675.0  820.0  697.0  306.0  28.0       2526  2013-03-31
2  Wind Gen(MU)    2.0   19.0   13.0    0.0   0.0         34  2013-03-31
3         Hydro  137.0   43.0   83.0   32.0   5.0        300  2013-04-01
4         Total  683.0  841.0  706.0  316.0  29.0       2575  2013-04-01

In [42]:
df.shape

(18251, 8)

In [43]:
df.columns

Index(['source', 'NR', 'WR', 'SR', 'ER', 'NER', 'All India', 'date'], dtype='object')

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18251 entries, 0 to 18250
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   source     18251 non-null  object
 1   NR         18251 non-null  float64
 2   WR         18251 non-null  float64
 3   SR         18251 non-null  float64
 4   ER         18251 non-null  float64
 5   NER        18251 non-null  float64
 6   All India  18251 non-null  int64
 7   date       18251 non-null  object
dtypes: float64(5), int64(1), object(2)
memory usage: 1.1+ MB

In [45]:
df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
df.columns

Index(['source', 'nr', 'wr', 'sr', 'er', 'ner', 'all_india', 'date'], dtype='object')

In [46]:
df["date"] = pd.to_datetime(df["date"], dayfirst=True)
df.head()

C:\Users\91821\AppData\Local\Temp\ipykernel_21568\3186691428.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["date"] = pd.to_datetime(df["date"], dayfirst=True)

         source     nr     wr     sr     er   ner  all_india       date
0         Hydro  139.0   43.0   72.0   30.0   7.0        292 2013-03-31
1         Total  675.0  820.0  697.0  306.0  28.0       2526 2013-03-31
2  Wind Gen(MU)    2.0   19.0   13.0    0.0   0.0         34 2013-03-31
3         Hydro  137.0   43.0   83.0   32.0   5.0        300 2013-04-01
4         Total  683.0  841.0  706.0  316.0  29.0       2575 2013-04-01

In [47]:
df_long = df.melt(
    id_vars=["date", "source"],
    value_vars=["nr", "wr", "sr", "er", "ner"],
    var_name="region",
    value_name="value"
)

df_long.head()

        date        source region  value
0 2013-03-31         Hydro     nr  139.0
1 2013-03-31         Total     nr  675.0
2 2013-03-31  Wind Gen(MU)     nr    2.0
3 2013-04-01         Hydro     nr  137.0
4 2013-04-01         Total     nr  683.0

In [48]:
df_long["source"] = df_long["source"].str.lower().str.strip()
df_long["region"] = df_long["region"].str.upper()

In [49]:
df_final = df_long.pivot_table(
    index=["date", "region"],
    columns="source",
    values="value"
).reset_index()

df_final.head()

source,date,region,coal,"gas, naptha & diesel",hydro,lignite,nuclear,"res (wind, solar, biomass & others)",solar gen (mu),thermal (coal & lignite),total,wind gen(mu)
0,2013-03-31,ER,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,306.0,0.0
1,2013-03-31,NER,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,28.0,0.0
2,2013-03-31,NR,NaN,NaN,139.0,NaN,NaN,NaN,NaN,NaN,675.0,2.0
3,2013-03-31,SR,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,697.0,13.0
4,2013-03-31,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,820.0,19.0

In [50]:
df.head()

         source     nr     wr     sr     er   ner  all_india       date
0         Hydro  139.0   43.0   72.0   30.0   7.0        292 2013-03-31
1         Total  675.0  820.0  697.0  306.0  28.0       2526 2013-03-31
2  Wind Gen(MU)    2.0   19.0   13.0    0.0   0.0         34 2013-03-31
3         Hydro  137.0   43.0   83.0   32.0   5.0        300 2013-04-01
4         Total  683.0  841.0  706.0  316.0  29.0       2575 2013-04-01

In [51]:
df[df["source"].str.contains("Solar", case=False, na=False)].head(20)

              source    nr     wr    sr    er   ner  all_india       date
2937  Solar Gen (MU)  1.99   9.65  16.0  0.03  0.02         28 2016-01-01
3737  Solar Gen (MU)  3.01  10.79   9.4  0.04  0.03         23 2016-09-27
3743  Solar Gen (MU)  3.43  10.64   8.4  0.00  0.01         22 2016-09-28
3747  Solar Gen (MU)  0.47  11.19   8.5  0.00  0.02         20 2016-09-29
3751  Solar Gen (MU)  0.35   9.67   9.4  0.00  0.02         19 2016-09-30
3755  Solar Gen (MU)  0.43   6.74  10.1  0.00  0.02         17 2016-10-01
3758  Solar Gen (MU)  0.12   8.02  12.2  0.04  0.02         20 2016-10-02
3763  Solar Gen (MU)  0.27   7.55  12.3  0.04  0.01         20 2016-10-03
3767  Solar Gen (MU)  0.14   6.91  12.0  0.02  0.02         19 2016-10-04
3770  Solar Gen (MU)  0.30   5.43  11.8  0.04  0.02         18 2016-10-05
3774  Solar Gen (MU)  0.45   7.22  12.4  0.04  0.02         20 2016-10-06
3777  Solar Gen (MU)  0.66   7.86  12.3  0.03  0.02         21 2016-10-07
3780  Solar Gen (MU)  0.62   8.90  11.7  0.03  0.02         21 2016-10-08
3784  Solar Gen (MU)  0.52  10.04  11.9  0.00  0.01         22 2016-10-09
3788  Solar Gen (MU)  0.64  10.56  13.2  0.00  0.01         24 2016-10-10
3794  Solar Gen (MU)  3.27  10.67  14.2  0.04  0.01         28 2016-10-11
3796  Solar Gen (MU)  2.81  11.26  12.3  0.04  0.01         26 2016-10-12
3800  Solar Gen (MU)  0.71  46.67  11.2  0.02  0.02         59 2016-10-13
3804  Solar Gen (MU)  3.75  10.54  13.1  0.02  0.01         27 2016-10-14
3810  Solar Gen (MU)  0.98  10.13  13.5  0.04  0.03         25 2016-10-15

In [52]:
df_final.columns

Index(['date', 'region', 'coal', 'gas, naptha & diesel', 'hydro', 'lignite',
       'nuclear', 'res (wind, solar, biomass & others)', 'solar gen (mu)',
       'thermal (coal & lignite)', 'total', 'wind gen(mu)'],
      dtype='object', name='source')

In [53]:
df_final.head(10)

source,date,region,coal,"gas, naptha & diesel",hydro,lignite,nuclear,"res (wind, solar, biomass & others)",solar gen (mu),thermal (coal & lignite),total,wind gen(mu)
0,2013-03-31,ER,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,306.0,0.0
1,2013-03-31,NER,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,28.0,0.0
2,2013-03-31,NR,NaN,NaN,139.0,NaN,NaN,NaN,NaN,NaN,675.0,2.0
3,2013-03-31,SR,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,697.0,13.0
4,2013-03-31,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,820.0,19.0
5,2013-04-01,ER,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,316.0,0.0
6,2013-04-01,NER,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,29.0,0.0
7,2013-04-01,NR,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,683.0,7.0
8,2013-04-01,SR,NaN,NaN,83.0,NaN,NaN,NaN,NaN,NaN,706.0,19.0
9,2013-04-01,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,841.0,21.0

In [54]:
df_final.isnull().sum()

source
date                                       0
region                                     0
coal                                    9905
gas, naptha & diesel                    7755
hydro                                      0
lignite                                 9905
nuclear                                 7755
res (wind, solar, biomass & others)     7755
solar gen (mu)                         15860
thermal (coal & lignite)               15320
total                                    535
wind gen(mu)                            9710
dtype: int64

In [55]:
df_final[df_final["solar gen (mu)"].notna()].head(10)

source,date,region,coal,"gas, naptha & diesel",hydro,lignite,nuclear,"res (wind, solar, biomass & others)",solar gen (mu),thermal (coal & lignite),total,wind gen(mu)
4845,2016-01-01,ER,NaN,NaN,20.0,NaN,NaN,NaN,0.03,NaN,321.0,0.0
4846,2016-01-01,NER,NaN,NaN,9.0,NaN,NaN,NaN,0.02,NaN,36.5,0.0
4847,2016-01-01,NR,NaN,NaN,102.5,NaN,NaN,NaN,1.99,NaN,836.0,8.0
4848,2016-01-01,SR,NaN,NaN,32.0,NaN,NaN,NaN,16.00,NaN,764.5,31.0
4849,2016-01-01,WR,NaN,NaN,38.5,NaN,NaN,NaN,9.65,NaN,962.0,23.5
6155,2016-09-27,ER,NaN,NaN,79.0,NaN,NaN,NaN,0.04,NaN,370.0,0.0
6156,2016-09-27,NER,NaN,NaN,22.0,NaN,NaN,NaN,0.03,NaN,43.0,0.0
6157,2016-09-27,NR,NaN,NaN,234.0,NaN,NaN,NaN,3.01,NaN,1045.0,23.0
6158,2016-09-27,SR,NaN,NaN,95.0,NaN,NaN,NaN,9.40,NaN,826.0,87.0
6159,2016-09-27,WR,NaN,NaN,46.0,NaN,NaN,NaN,10.79,NaN,947.0,46.0

In [56]:
df_final.columns = (
    df_final.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

In [57]:
df_final.columns

Index(['date', 'region', 'coal', 'gas,_naptha_&_diesel', 'hydro', 'lignite',
       'nuclear', 'res_wind,_solar,_biomass_&_others', 'solar_gen_mu',
       'thermal_coal_&_lignite', 'total', 'wind_genmu'],
      dtype='object', name='source')

In [58]:
df_final.columns = (
    df_final.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("&", "and", regex=False)
)

df_final.columns

Index(['date', 'region', 'coal', 'gas_naptha_and_diesel', 'hydro', 'lignite',
       'nuclear', 'res_wind_solar_biomass_and_others', 'solar_gen_mu',
       'thermal_coal_and_lignite', 'total', 'wind_genmu'],
      dtype='object', name='source')

In [59]:
df_final.columns.name = None
df_final.head()

,date,region,coal,gas_naptha_and_diesel,hydro,lignite,nuclear,res_wind_solar_biomass_and_others,solar_gen_mu,thermal_coal_and_lignite,total,wind_genmu
0,2013-03-31,ER,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,306.0,0.0
1,2013-03-31,NER,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,28.0,0.0
2,2013-03-31,NR,NaN,NaN,139.0,NaN,NaN,NaN,NaN,NaN,675.0,2.0
3,2013-03-31,SR,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,697.0,13.0
4,2013-03-31,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,820.0,19.0

In [60]:
df_final[[
    "date",
    "region",
    "hydro",
    "total",
    "wind_genmu",
    "solar_gen_mu"
]].head(10)

        date region  hydro  total  wind_genmu  solar_gen_mu
0 2013-03-31     ER   30.0  306.0         0.0           NaN
1 2013-03-31    NER    7.0   28.0         0.0           NaN
2 2013-03-31     NR  139.0  675.0         2.0           NaN
3 2013-03-31     SR   72.0  697.0        13.0           NaN
4 2013-03-31     WR   43.0  820.0        19.0           NaN
5 2013-04-01     ER   32.0  316.0         0.0           NaN
6 2013-04-01    NER    5.0   29.0         0.0           NaN
7 2013-04-01     NR  137.0  683.0         7.0           NaN
8 2013-04-01     SR   83.0  706.0        19.0           NaN
9 2013-04-01     WR   43.0  841.0        21.0           NaN

In [61]:
df_final[df_final["total"].isna()][["date", "region"]].head(20)

           date region
7220 2017-05-08     ER
7221 2017-05-08    NER
7222 2017-05-08     NR
7223 2017-05-08     SR
7224 2017-05-08     WR
7225 2017-05-09     ER
7226 2017-05-09    NER
7227 2017-05-09     NR
7228 2017-05-09     SR
7229 2017-05-09     WR
7230 2017-05-10     ER
7231 2017-05-10    NER
7232 2017-05-10     NR
7233 2017-05-10     SR
7234 2017-05-10     WR
7235 2017-05-11     ER
7236 2017-05-11    NER
7237 2017-05-11     NR
7238 2017-05-11     SR
7239 2017-05-11     WR

In [62]:
for col in df_final.columns:
    if col not in ["date", "region"]:
        non_null = df_final[df_final[col].notna()]
        if len(non_null) > 0:
            print(f"{col}: starts from {non_null['date'].min().date()} | non-null rows = {len(non_null)}")
        else:
            print(f"{col}: no non-null values")

coal: starts from 2018-11-29 | non-null rows = 7565
gas_naptha_and_diesel: starts from 2017-05-26 | non-null rows = 9715
hydro: starts from 2013-03-31 | non-null rows = 17470
lignite: starts from 2018-11-29 | non-null rows = 7565
nuclear: starts from 2017-05-26 | non-null rows = 9715
res_wind_solar_biomass_and_others: starts from 2017-05-26 | non-null rows = 9715
solar_gen_mu: starts from 2016-01-01 | non-null rows = 1610
thermal_coal_and_lignite: starts from 2017-05-26 | non-null rows = 2150
total: starts from 2013-03-31 | non-null rows = 16935
wind_genmu: starts from 2013-03-31 | non-null rows = 7760

In [63]:
df_final.shape

(17470, 12)

In [64]:
df_final.head(10)

,date,region,coal,gas_naptha_and_diesel,hydro,lignite,nuclear,res_wind_solar_biomass_and_others,solar_gen_mu,thermal_coal_and_lignite,total,wind_genmu
0,2013-03-31,ER,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,306.0,0.0
1,2013-03-31,NER,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,28.0,0.0
2,2013-03-31,NR,NaN,NaN,139.0,NaN,NaN,NaN,NaN,NaN,675.0,2.0
3,2013-03-31,SR,NaN,NaN,72.0,NaN,NaN,NaN,NaN,NaN,697.0,13.0
4,2013-03-31,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,820.0,19.0
5,2013-04-01,ER,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,316.0,0.0
6,2013-04-01,NER,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,29.0,0.0
7,2013-04-01,NR,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,683.0,7.0
8,2013-04-01,SR,NaN,NaN,83.0,NaN,NaN,NaN,NaN,NaN,706.0,19.0
9,2013-04-01,WR,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,841.0,21.0

In [65]:
df_final.tail(10)

,date,region,coal,gas_naptha_and_diesel,hydro,lignite,nuclear,res_wind_solar_biomass_and_others,solar_gen_mu,thermal_coal_and_lignite,total,wind_genmu
17460,2023-03-30,ER,726.0,0.0,28.0,0.0,0.0,7.0,NaN,NaN,761.0,NaN
17461,2023-03-30,NER,11.0,24.0,11.0,0.0,0.0,1.0,NaN,NaN,47.0,NaN
17462,2023-03-30,NR,671.0,10.0,112.0,27.0,27.0,135.0,NaN,NaN,982.0,NaN
17463,2023-03-30,SR,720.0,6.0,68.0,67.0,76.0,177.0,NaN,NaN,1115.0,NaN
17464,2023-03-30,WR,1415.0,17.0,41.0,20.0,32.0,153.0,NaN,NaN,1678.0,NaN
17465,2023-03-31,ER,703.0,0.0,23.0,0.0,0.0,6.0,NaN,NaN,733.0,NaN
17466,2023-03-31,NER,9.0,25.0,10.0,0.0,0.0,1.0,NaN,NaN,45.0,NaN
17467,2023-03-31,NR,588.0,10.0,113.0,30.0,30.0,161.0,NaN,NaN,932.0,NaN
17468,2023-03-31,SR,676.0,463.0,61.0,70.0,76.0,196.0,NaN,NaN,1543.0,NaN
17469,2023-03-31,WR,1359.0,15.0,28.0,21.0,32.0,168.0,NaN,NaN,1623.0,NaN

In [66]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17470 entries, 0 to 17469
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   date                               17470 non-null  datetime64[ns]
 1   region                             17470 non-null  object
 2   coal                               7565 non-null   float64
 3   gas_naptha_and_diesel              9715 non-null   float64
 4   hydro                              17470 non-null  float64
 5   lignite                            7565 non-null   float64
 6   nuclear                            9715 non-null   float64
 7   res_wind_solar_biomass_and_others  9715 non-null   float64
 8   solar_gen_mu                       1610 non-null   float64
 9   thermal_coal_and_lignite           2150 non-null   float64
 10  total                              16935 non-null  float64
 11  wind_genmu                         7760 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(1)
memory usage: 1.6+ MB

In [67]:
df_final.isnull().sum().sort_values(ascending=False)

solar_gen_mu                         15860
thermal_coal_and_lignite             15320
coal                                  9905
lignite                               9905
wind_genmu                            9710
nuclear                               7755
gas_naptha_and_diesel                 7755
res_wind_solar_biomass_and_others     7755
total                                  535
region                                   0
date                                     0
hydro                                    0
dtype: int64

In [68]:
df_final.duplicated(subset=["date", "region"]).sum()

np.int64(0)

In [69]:
df_final["region"].unique()

array(['ER', 'NER', 'NR', 'SR', 'WR'], dtype=object)

In [70]:
df_final = df_final.sort_values(["date", "region"]).reset_index(drop=True)
df_final.to_csv("../data/processed/full_generation_pivot.csv", index=False)